#Comments

name: Wood_CI

#Задаем глобальные переменные
env:
  APPLICATION_NAME: "me-file"
  PACKAGE_NAME: "docker-image-${{ github.sha }}" #переменная равна коду коммита
on:
  push:
    branches:
      - main
jobs: #ansible block
  my-test:
    runs-on: ubuntu-latest #docker FROM
    steps: #ansible tasks
      - name: gi clone my repo
        uses: actions/checkout@v1 # copy repo to contsiner
      - name: Print hello world
        run: ls -la # ansible shell
      - name: Execute commands
        run: |
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          echo "hello3"

  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-test] # blocks dependencу

#job env
    env:
      VAR1: "variable 1"

    steps:
      - name: Execute commands
        run: |
          echo "Package name: ${{ env.PACKAGE_NAME }}"
          echo "hellovdvdvdvdv"
#local env for step (task)
      - name: print local env
        run: |
          echo "var1= ${{ env.VAR1 }}"
          echo "Var_local = $LOCAL_VAR"
        env:
          LOCAL_VAR: "SUPER local env"