#Comments

name: Wood_CI

#Задаем глобальные переменные

env:
  APPLICATION_NAME: "me-file"
  PACKAGE_NAME: "docker-image-${{ github.sha }}" #переменная равна коду коммита
on:
  push:
    branches:
      - main
jobs: #ansible block
  my-test:
    runs-on: ubuntu-latest #docker FROM
    steps: #ansible tasks
      - name: Print hello world
        run: echo "Hello world" # ansible shell
      - name: Execute commands
        run: |
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          echo "hello3"

   my-deploy:
    runs-on: ubuntu-latest
    needs: [my-test] # blocks dependencу
    steps:
      - name: Execute commands
        run: |
          echo "Package name: ${{ env.PACKAGE_NAME }}"
          echo "hellovdvdvdvdv"